export const PERMISSION_MANAGE_USER = "MANAGE_USER";
export const PERMISSION_MANAGE_MASTER_DATA = "MANAGE_MASTER_DATA";
export const PERMISSION_VIEW_ALL_LEAD = "VIEW_ALL_LEAD";
export const PERMISSION_MANAGE_ALL_LEAD = "MANAGE_ALL_LEAD";
export const PERMISSION_VIEW_BRANCH_LEAD = "VIEW_BRANCH_LEAD";
export const PERMISSION_MANAGE_OWN_LEAD = "MANAGE_OWN_LEAD";
export const PERMISSION_VIEW_DASHBOARD = "VIEW_DASHBOARD";
